name: run tests
on:
  push:
  schedule:
    - cron: "0 1 * * *"

jobs:
#  lint:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '^3.12'

#      - name: upgrade pip
#        run: python -m pip install --upgrade pip

      - name: install pipx
        run: |
          sudo apt update
          sudo apt install pipx
          pipx ensurepath

      - name: install poetry
#        run: pip3 install poetry
        run: pipx install poetry==1.8.4

      - name: install dependencies
        run: poetry install

      - name: run playwright
        run: poetry run playwright install

      - name: run tests
        run: poetry run pytest

#  allure-report:
#    needs: [tests]
#      -