name: run tests
on:
  push:
  schedule:
    - cron: "0 1 * * *"

jobs:
#  lint:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
#      - name: Install dependencies
#        run: ???
      - name: run tests
        run: poetry run pytest
#  allure-report:
#    needs: [tests]
#      -