name: run tests
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 2 1,3,6,9,11,12,14,16,19,20,21,23,25,26,28,31 * *"

jobs:
  #  lint:

  setup_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '^3.12'

      - name: Install poetry
        run: |
          sudo apt update
          sudo apt install pipx
          pipx ensurepath
          pipx install poetry==1.8.4

      - name: Install dependencies
        run: | 
          poetry install --no-interaction --no-ansi
          poetry run playwright install --with-deps

      - name: Run tests
        if: always()
        run: poetry run pytest
        continue-on-error: true

      - name: Upload "allure-results"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
          retention-days: 1

  allure_report:
    runs-on: ubuntu-latest
    needs: [ setup_and_test ]
    steps:
      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        id: download
        if: always()
        continue-on-error: true
        with:
          name: allure-results
          path: allure-results

      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

