name: run tests
on:
  push:
  schedule:
    - cron: "0 1 * * *"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
#      - name: Install dependencies
#        run: ???