name: run tests
on:
  push:
  schedule:
    - cron: "0 1 * * *"

jobs:
#  lint:

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '^3.12'

#        poetry config virtualenvs.in-project true  # сохраняет поетри в папку .venv внутри проекта. Удобно затем удалять

      - name: install pipx
        run: |
          sudo apt update
          sudo apt install pipx
          pipx ensurepath

      - name: install poetry
        run: pipx install poetry==1.8.4

      - name: install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: run playwright
        run: poetry run playwright install --with-deps

#      - name: run tests
#        run: poetry run pytest

  tests:
    runs-on: ubuntu-latest
    needs: [ setup ]

    steps:
      - name: run tests
        run: poetry run pytest


  allure_report:
    runs-on: ubuntu-latest
    needs: [ tests ]




#  allure-report:
#    needs: [tests]
#      steps:
#
#      -